### ISSUE TITLE
MemoryStore layer

### ISSUE THREAD

**Issue by Kikobeats** [dotcypress/micro-ratelimit#1]
Could be interesting provide a way for support different memory store  transports.

The current memory store implementation is based on memory, but normally they are backed on redis or something similar.

For do that simply define an API of the basic methods that a memory store needs to implement and expose it in the constructor.

**Comment by dotcypress** [comment]
I'm afraid, current implementation relies on sync store, and async/persistent stores will change all library code.

I want to save library tiny.
Anyway, feel free to fork and make persistent version 😉
